def gv

pipeline {
    agent any
    parameters {
        choice(name:'VERSION', choices:['1.1', '1.2', '1.4'], description: "Choose the version you want to deploy")
        booleanParam(name: 'execute tests', defaultValue: true, description: " ")
    }

    stages {

        stage ("init") {
            steps {
                script {
                    gv = load "script.groovy"
                }

            }
        }
        stage ("Build") {
            steps {
                script {
                    gv.buildApp()
                }
                echo 'building the application based on server you selected'

            }
        }
        
        stage ("Test") {
            when {
                expression {
                    params.executeTests
                }
            }
            steps {
                script {
                    gv.testApp()
                }
                echo 'Testing the App'

            }
        }
        stage ("Deploying") {
            input {
                message "Select which env you have to deploy to ?"
                ok "Done"
                parameters {
                    choice(name:'ENV', choices:['sbx', 'preprod','Prod'], description: "Choose the version you want to deploy")

                }
            }

            steps {
                script {
                    gv.deployApp()
                }
                echo 'Deploying the App'
                echo "Deploying the env ${params.ENV}"

            }
            
        }
        
    }
    

}
