def gv

pipeline {
    agent any
    parameters {
        choice(name: 'VERSION', choices: ['1.1', '1.2', '1.4'], description: "Choose the version you want to deploy")
        booleanParam(name: 'executeTests', defaultValue: true, description: "Run tests?")
    }

    stages {

        stage("Init") {
            steps {
                script {
                    try {
                        // Adjusted to the correct relative path
                        gv = load "Jenkins/test/script.groovy"
                        echo "Loaded script.groovy successfully."
                    } catch (Exception e) {
                        error "Failed to load script.groovy: ${e.message}"
                    }
                }
            }
        }

        stage("Build") {
            steps {
                script {
                    gv.buildApp()
                }
                echo 'Build stage completed.'
            }
        }
        
        stage("Test") {
            when {
                expression {
                    params.executeTests
                }
            }
            steps {
                script {
                    gv.testApp()
                }
                echo 'Test stage completed.'
            }
        }

        stage("Deploying") {
            input {
                message "Select which environment you want to deploy to."
                ok "Done"
                parameters {
                    choice(name: 'ENV', choices: ['sbx', 'preprod', 'Prod'], description: "Select the environment to deploy to.")
                }
            }
            steps {
                script {
                    gv.deployApp(params.VERSION)
                }
                echo "Deploying to environment: ${params.ENV}"
            }
        }
    }
}
