
### `Jenkinsfile`

```groovy
pipeline {
    agent any

    environment {
        // Defining environment variables
        myString = "Hello Syed"
        myNumber = 10
        myBool = true
    }

    stages {
        stage("Demo") {
            steps {
                // Printing environment variables to the console
                echo "myString : ${myString}"
                echo "myNumber : ${myNumber}"
                echo "myBool : ${myBool}"
            }
        }
    }
}
