
pipeline {
    agent any

    stages {
        stage('Stage-1') {
            steps {
                echo "At Stage 1"
            }
        }
        stage('Stage-2') {
            steps {
                echo "At Stage 2"
            }
        }
        stage('Stage-3') {
            steps {
                echo "At Stage 3"
            }
        }
        stage('Stage-4') {
            steps {
                echo "At Stage 4"
            }
        }
        stage('Stage-5') {
            steps {
                echo "At Stage 5"
            }
        }
    }
}
